version: '3.4'

services:
  db:
    image: postgres:14.7
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
    env_file: .env

  data-api:
    build: ./data-api/
    volumes:
      - ./data-api:/code
      - ./tmp/dataset_cache:/root/.cache/huggingface/datasets/
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      web:
        condition: service_healthy

  web:
    build:
      context: ./next 
      dockerfile: Dockerfile.dev
      args:
        EXTERNAL_API: ${NEXT_PUBLIC_API_URL}
    image: web-image:latest
    volumes:
      - ./next/src:/app/src
      - ./next/__test__:/app/__test__
    command: /bin/sh /start.sh
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      DATA_PROBLEM: ${DATA_PROBLEM}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
